{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:8:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeCannot read property '0' of undefined","stack":"TypeError: Cannot read property '0' of undefined\n    at Function.init (/Users/dip/dipankar/dutils/dist/dtelemetry.js:34:36)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:9:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"[ERROR] Error"}
{"level":"error","message":"[FETAL] Some exception occurred in the codeTest","stack":"Error: Test\n    at Object.<anonymous> (/Users/dip/dipankar/dutils/dist/test.js:16:16)\n    at Module._compile (internal/modules/cjs/loader.js:1144:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\n    at Module.load (internal/modules/cjs/loader.js:996:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
